#!/bin/bash

comment ()
{
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
}

clear_global_cache ()
{
  rm -rf $HOME/.ied_cache
  return $?
}

require_package ()
{
  node -e "require('assert')(require(\"${package}\"))";
  return $?
}

install_package ()
{
  local sandbox_dir="sandbox/install_${package}"

  rm -rf $sandbox_dir
  mkdir -p $sandbox_dir
  cd $sandbox_dir

  ied install ${package}
}

# Run the test suite
main ()
{
  local error_count=0
  local success_count=0

  local main_dir=$(pwd)

  while read package; do
    comment "testing ${package}"
    clear_global_cache
    install_package $package
    require_package ${package}

    if [ $? -eq 0 ]; then
      comment "SUCCESS"
      ((success_count++))
    else
      comment "ERROR"
      ((error_count++))
    fi
    echo

    cd $main_dir
  done <test/packages.txt

  echo "--------------------------------------------------------------------------------"
  comment "SUCCESS: ${success_count}"
  comment "ERROR:   ${error_count}"

  exit ${error_count}
}

main "$@"
